version: "3"
services:
  main-app:
    build:
      context: ./002-console
      dockerfile: 002-console.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - counter-service
  counter-service:
    build:
      context: ./counterBooks
      dockerfile: counterBooks.Dockerfile
    volumes:
      - ./counterBooks/data.json:/app/data.json:rw
